name: AtelierConstruction
version: 1.0
auther: firiz
main: net.firiz.atelierconstruction.AtelierConstructionV2
api-version: 1.16
depend: [ AtelierCommonAPI ]
commands:
    asm:
        description: asm
        usage: /asm
    fb:
        description: fb
        usage: /fb
    customblocks:
        description: customblocks
        usage: /customblocks
        aliases: [cb, cbs]