name: AtelierCommonAPI
version: 1.0
auther: firiz
main: net.firiz.ateliercommonapi.AtelierCommonAPI
api-version: 1.16
commands:
  ateliercommonapi:
    description: ateliercommonapi
    usage: /ateliercommonapi
  loops:
    description: loops
    usage: /loops